baseURL = 'https://www.cantara.app'
title = 'Cantara'
theme = 'hugo-theme-relearn'
canonifyurls = true

defaultContentLanguage = "en"

[outputs]
    home = [ "html", "rss", "search"]

[Languages]

    [Languages.en]
    title = 'Cantara'
    weight = 1
    languageName = 'English'

    [Languages.de]
    title = 'Cantara'
    weight = 2
    languageName = 'Deutsch'


    [[Languages.en.menu.shortcuts]]
    name = "<i class='fab fa-github'></i> Github Repository"
    identifier = "gh"
    url = "https://github.com/reckel-jm/cantara"
    weight = 10

    [[Languages.en.menu.shortcuts]]
        name = "<i class='fas fa-bookmark'></i> Imprint & Data Privacy"
        identifier = "imprint"
        url = "/imprint"
        weight = 30

[params]
# Define words per minute to approximate reading time
	wpm = 250
